repos:
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
    -   id: nbstripout
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        args: [--install-types, --non-interactive, --ignore-missing-imports, --show-error-codes]
