name: tfidf_model1
fname: tfidf_model.bin
analyzer: word
max_features: 10_000
norm: None
max_iter: 10_000
lowercase: True
ngram_range: (1, 1)
min_df: 1
max_df: 1
use_idf: True
smooth_idf: True
sublinear_tf: False
