defaults:
  - label_model: label_model
  - tfidf_model: tfidf_model
  - transformer_model: xlmr-base3
  - data: offensive
  - _self_

models:
  dir: models

seed: 4242
testing: False
train_split_truncation_length: -1
