defaults:
  - tfidf_model: tfidf_model
  - transformer_model: mps_transformer_model
  - _self_

data:
  raw_dir: data/raw
  processed_dir: data/processed
  final_dir: data/final

models:
  dir: models

seed: 4242
test: False
